"""Render registered reported figures as LaTeX macro definitions.

The manuscript never types a quantitative value. It calls ``\\figval{<id>}``,
and this generator writes the value that the registry currently holds. A figure
that is stale, superseded, or bound to a superseded pipeline is not emitted, so
the LaTeX build fails rather than typesetting a number the registry has already
retired.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:  # script or module
    from validate_registry import (
        _format_figure_value,
        load_registry,
        validate_registry,
    )
except ModuleNotFoundError:  # pragma: no cover - import shim
    from tools.validate_registry import (  # type: ignore[no-redef]
        _format_figure_value,
        load_registry,
        validate_registry,
    )

HEADER = (
    "% Generated by tools/render_figure_macros.py -- do not edit.\n"
    "% Every value below is the registry's current value for that figure id.\n"
)


def render(root: Path, checkpoint: str = "C") -> tuple[str, list[str]]:
    registry = load_registry(root)
    report = validate_registry(registry, checkpoint)
    figures = report["state"]["reported_figures"]
    lines: list[str] = []
    withheld: list[str] = []
    for figure_id in sorted(figures):
        figure = figures[figure_id]
        if figure.get("_stale_reasons") or figure.get("status") not in (
            None,
            "current",
        ):
            withheld.append(figure_id)
            continue
        value = figure.get("value")
        if value is None:
            withheld.append(figure_id)
            continue
        shown = _format_figure_value(value, figure.get("display"))
        lines.append(f"\\defineFigureValue{{{figure_id}}}{{{shown}}}")
    return HEADER + "\n".join(lines) + "\n", withheld


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("registry", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--checkpoint", default="C")
    args = parser.parse_args(argv)

    body, withheld = render(args.registry, args.checkpoint)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body, encoding="utf-8")
    for figure_id in withheld:
        print(f"withheld: {figure_id}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
